name: 'ZJU-nCov-Hitcarder Action'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        include:
          - username: ZJU_USERNAME #pengshiyi
            password: ZJU_PASSWORD
            dingtalk_token: DINGTALK_TOKEN
            pushplus_token: PUSHPLUS_TOKEN
            serverchan_key: SERVERCHAN_KEY
          - username: ZJU_USERNAME2 #fengzhe
            password: ZJU_PASSWORD2
            dingtalk_token: DINGTALK_TOKEN2
            pushplus_token: PUSHPLUS_TOKEN2
            serverchan_key: SERVERCHAN_KEY2
          - username: ZJU_USERNAME3 #chenrunze
            password: ZJU_PASSWORD3
            dingtalk_token: DINGTALK_TOKEN3
            pushplus_token: PUSHPLUS_TOKEN3
            serverchan_key: SERVERCHAN_KEY3
          - username: ZJU_USERNAME4 #wutianxiang
            password: ZJU_PASSWORD4
            dingtalk_token: DINGTALK_TOKEN4
            pushplus_token: PUSHPLUS_TOKEN4
            serverchan_key: SERVERCHAN_KEY4
          - username: ZJU_USERNAME5 #nihuwei
            password: ZJU_PASSWORD5
            dingtalk_token: DINGTALK_TOKEN5
            pushplus_token: PUSHPLUS_TOKEN5
            serverchan_key: SERVERCHAN_KEY5
          - username: ZJU_USERNAME6 #zhuchengxi
            password: ZJU_PASSWORD6
            dingtalk_token: DINGTALK_TOKEN6
            pushplus_token: PUSHPLUS_TOKEN6
            serverchan_key: SERVERCHAN_KEY6
    steps:
      - name: Working
        uses: Long0x0/zju-ncov-hitcarder@master
        with:
          username: ${{ secrets[matrix.username] }}
          password: ${{ secrets[matrix.password] }}
          dingtalk_token: ${{ secrets[matrix.dingtalk_token] }}
          pushplus_token: ${{ secrets[matrix.pushplus_token] }}
          serverchan_key: ${{ secrets[matrix.serverchan_key] }}
